- name: "App setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: "Java setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml


- name: "System service"
  ansible.builtin.import_role:
    name: common
    tasks_from: service-setup.yaml

- name: install dependencie
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: "Start the service"
  ansible.builtin.service:
    name: shipping
    state: restarted
    eanbled: yes