 - name: "Copying repo"
   ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

    
 - name: "Installing rabbitmq"
   ansible.builtin.dnf:
      name: rabbitmq-server
      state: present

 - name: "start service"
   ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes 

 - name: "Setting rabbitmq password"
   community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present